### Request /login endpoint => success
POST {{baseUrl}}/system/oauth2-client/create
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "id": "1",
  "secret": "admin123",
  "name": "Focela",
  "logo": "https://platform.focela.com/favicon.ico",
  "description": "Description",
  "status": 0,
  "accessTokenValiditySeconds": 180,
  "refreshTokenValiditySeconds": 8640,
  "redirectUris": ["https://platform.focela.com"],
  "autoApprove": true,
  "authorizedGrantTypes": ["password"],
  "scopes": ["user_info"],
  "authorities": ["system:user:query"],
  "resource_ids": ["1024"],
  "additionalInformation": "{}"
}
