package com.focela.platform.test.core.utils;

import cn.hutool.core.util.ArrayUtil;
import cn.hutool.core.util.ReflectUtil;
import com.focela.platform.common.exception.ErrorCode;
import com.focela.platform.common.exception.ServiceException;
import com.focela.platform.common.exception.utils.ServiceExceptionUtils;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.function.Executable;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.Objects;

import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Unit test assertion utility class.
 */
public class AssertUtils {

    /**
     * Compare whether the properties of two objects are equal.
     *
     * Note: if a property exists on expected but not on actual, it is ignored.
     *
     * @param expected expected object
     * @param actual actual object
     * @param ignoreFields properties to ignore
     */
    public static void assertPojoEquals(Object expected, Object actual, String... ignoreFields) {
        Field[] expectedFields = ReflectUtil.getFields(expected.getClass());
        Arrays.stream(expectedFields).forEach(expectedField -> {
            // ignore $jacocoData properties auto-generated by jacoco
            if (expectedField.isSynthetic()) {
                return;
            }
            // skip properties in the ignore list
            if (ArrayUtil.contains(ignoreFields, expectedField.getName())) {
                return;
            }
            // ignore properties that do not exist
            Field actualField = ReflectUtil.getField(actual.getClass(), expectedField.getName());
            if (actualField == null) {
                return;
            }
            // compare
            Assertions.assertEquals(
                    ReflectUtil.getFieldValue(expected, expectedField),
                    ReflectUtil.getFieldValue(actual, actualField),
                    String.format("Field(%s) does not match", expectedField.getName())
            );
        });
    }

    /**
     * Compare whether the properties of two objects are equal.
     *
     * Note: if a property exists on expected but not on actual, it is ignored.
     *
     * @param expected expected object
     * @param actual actual object
     * @param ignoreFields properties to ignore
     * @return whether they are equal
     */
    public static boolean isPojoEquals(Object expected, Object actual, String... ignoreFields) {
        Field[] expectedFields = ReflectUtil.getFields(expected.getClass());
        return Arrays.stream(expectedFields).allMatch(expectedField -> {
            // skip properties in the ignore list
            if (ArrayUtil.contains(ignoreFields, expectedField.getName())) {
                return true;
            }
            // ignore properties that do not exist
            Field actualField = ReflectUtil.getField(actual.getClass(), expectedField.getName());
            if (actualField == null) {
                return true;
            }
            return Objects.equals(ReflectUtil.getFieldValue(expected, expectedField),
                    ReflectUtil.getFieldValue(actual, actualField));
        });
    }

    /**
     * Execute the method and verify the thrown ServiceException matches the expected error.
     *
     * @param executable executable that should throw a business exception
     * @param errorCode error code object
     * @param messageParams message parameters
     */
    public static void assertServiceException(Executable executable, ErrorCode errorCode, Object... messageParams) {
        // invoke the method
        ServiceException serviceException = assertThrows(ServiceException.class, executable);
        // verify the error code
        Assertions.assertEquals(errorCode.getCode(), serviceException.getCode(), "error code mismatch");
        String message = ServiceExceptionUtils.doFormat(errorCode.getCode(), errorCode.getMsg(), messageParams);
        Assertions.assertEquals(message, serviceException.getMessage(), "error message mismatch");
    }

}
