name: wireguard

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ${WIREGUARD_DATA_DIR:-./data}:/config
      - /lib/modules:/lib/modules:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - SERVERURL=${WG_SERVER_URL:-auto}
      - SERVERPORT=${WG_SERVER_PORT:-51820}
      - PEERS=${WG_PEERS:-5}
      - PEERDNS=${WG_PEER_DNS:-auto}
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=10.13.13.0/24
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
