### Get tenant ID /admin-api/system/get-id-by-name
GET {{baseUrl}}/system/tenant/get-id-by-name?name=Focela

### Create tenant /admin-api/system/tenant/create
POST {{baseUrl}}/system/tenant/create
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "name": "Focela",
  "contactName": "Focela",
  "contactMobile": "15601691300",
  "status": 0,
  "domain": "https://platform.focela.com",
  "packageId": 110,
  "expireTime": 1699545600000,
  "accountCount": 20,
  "username": "admin",
  "password": "123321"
}
